CREATE TABLE SR_MONITOR
(
  TYPE                  VARCHAR2(128 BYTE),
  NAME                  VARCHAR2(128 BYTE),
  REV                   VARCHAR2(128 BYTE),
  STATE                 VARCHAR2(128 BYTE),
  MOD_TIMESTAMP         DATE,
  REPLICATION_TIMESTAMP DATE
)
NOCOMPRESS 
TABLESPACE SR_TBS
RESULT_CACHE (MODE DEFAULT)
LOGGING;




GRANT SELECT ON SR_MONITOR TO PLMPRD3ADMIN_SELECT_ROLE;

GRANT SELECT ON SR_MONITOR TO PLMPRD3ADMIN_SELECT_ROLE2;

GRANT SELECT ON SR_MONITOR TO SIMP_READ;